#ifndef __APP_GAME_TYPES_H__
#define __APP_GAME_TYPES_H__

#include <yuu/utils.h>

namespace app::game {

	enum SpritesheetHandler {
		KARU_SPRITESHEET,
		GRID_SPRITESHEET,
		COIN_SPRITESHEET,
		SPRITESHEET_BAT,
		SPRITESHEET_SKELETON,
		SPRITESHEET_FROG,
		SPRITESHEET_GHOST,
	};
	enum TextureHandler {
		BLANK_TEXTURE,
		KARU_TEXTURE,
		GRID_TEXTURE,
		COIN_TEXTURE,
		TEXTURE_BAT,
		TEXTURE_SKELETON,
		FROG_TEXTURE,
		TEXTURE_GHOST,
		SWORD_TEXTURE,
		ZERO, ONE, TWO, THREE, FOUR,
		FIVE, SIX, SEVEN, EIGHT, NINE,
		TEXT_SCORE,
		TEXT_START,
		TEXT_GAMEOVER,
		MAX
	};
}

#endif